# Generated by Django 4.2.16 on 2024-11-27 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('assignment_name', models.CharField(max_length=100)),
                ('work_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('assignment_name', models.CharField(max_length=255)),
                ('time_spent', models.IntegerField()),
                ('completed_on_time', models.CharField(choices=[('yes', 'はい'), ('no', 'いいえ')], max_length=10)),
                ('difficulty', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('no_time', '時間がなかった'), ('took_too_long', '思ったより時間がかかった'), ('couldnt_focus', '集中できなかった'), ('lack_of_motivation', 'やる気が出なかった'), ('unexpected_plans', '予想外の予定が入った'), ('health_issues', '体調不良'), ('other', 'その他')], max_length=50, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.task')),
            ],
        ),
    ]
