# Generated by Django 4.2.16 on 2024-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
