# Generated by Django 4.2.16 on 2024-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='work_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
