# Generated by Django 4.2.16 on 2024-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_completedtask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='user',
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='reason',
            field=models.CharField(blank=True, choices=[('時間がなかった', '時間がなかった'), ('思ったより時間がかかった', '思ったより時間がかかった'), ('集中できなかった', '集中できなかった'), ('やる気が出なかった', 'やる気が出なかった'), ('予想外の予定が入った', '予想外の予定が入った'), ('体調不良', '体調不良'), ('その他', 'その他')], max_length=50, null=True),
        ),
    ]
